# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/car_detect/car_detect.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==car_detect || ORIG_REF_NAME==car_detect} -quiet] -quiet

# IP: bd/car_detect/ip/car_detect_processing_system7_0_0/car_detect_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==car_detect_processing_system7_0_0 || ORIG_REF_NAME==car_detect_processing_system7_0_0} -quiet] -quiet

# IP: bd/car_detect/ip/car_detect_axi_gpio_0_0/car_detect_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==car_detect_axi_gpio_0_0 || ORIG_REF_NAME==car_detect_axi_gpio_0_0} -quiet] -quiet

# IP: bd/car_detect/ip/car_detect_auto_pc_0/car_detect_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==car_detect_auto_pc_0 || ORIG_REF_NAME==car_detect_auto_pc_0} -quiet] -quiet

# IP: bd/car_detect/ip/car_detect_ps7_0_axi_periph_0/car_detect_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==car_detect_ps7_0_axi_periph_0 || ORIG_REF_NAME==car_detect_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/car_detect/ip/car_detect_rst_ps7_0_50M_0/car_detect_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==car_detect_rst_ps7_0_50M_0 || ORIG_REF_NAME==car_detect_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/520_lab/FInal_project/hardware/car_detector/car_detector.gen/sources_1/bd/car_detect/car_detect_ooc.xdc
