# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/520_lab/FInal_project/hardware/car_detector/car_detector.srcs/sources_1/bd/car_detect/ip/car_detect_auto_pc_0/car_detect_auto_pc_0.xci
# IP: The module: 'car_detect_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/520_lab/FInal_project/hardware/car_detector/car_detector.gen/sources_1/bd/car_detect/ip/car_detect_auto_pc_0/car_detect_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'car_detect_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/520_lab/FInal_project/hardware/car_detector/car_detector.srcs/sources_1/bd/car_detect/ip/car_detect_auto_pc_0/car_detect_auto_pc_0.xci
# IP: The module: 'car_detect_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/520_lab/FInal_project/hardware/car_detector/car_detector.gen/sources_1/bd/car_detect/ip/car_detect_auto_pc_0/car_detect_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'car_detect_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
